name: SellPlugin
version: 1.20.0
main: nl.sell.SellPlugin
api-version: '1.21'
depend: [Vault]
softdepend: [packetevents, PlaceholderAPI]
commands:
  sell:
    description: Open het verkoopmenu
    usage: /sell [history|worth|multiplier|language|reload|status|global <x>]
  worth:
    description: Bekijk de prijs van elk item
    usage: /worth [item|hand]
permissions:
  sell.*:
    description: Alle rechten van de plugin
    default: op
    children:
      sell.use: true
      sell.worth: true
      sell.history: true
      sell.multiplier: true
      sell.admin: true
  sell.use:
    description: /sell (het verkoopmenu openen)
    default: true
  sell.worth:
    description: /worth en /sell worth
    default: true
  sell.history:
    description: /sell history
    default: true
  sell.multiplier:
    description: /sell multiplier
    default: true
  sell.admin:
    description: /sell reload, status, global en language
    default: op
